services:
  nginx:
    image: nginx:alpine
    container_name: nginx_gateway
    ports:
      - "80:80" # only Nginx is publicly exposed
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    restart: always

  app:
    build: .
    container_name: fastapi_app
    # ports: remove host port exposure
    #   - "8000:8000"   # FastAPI is still reachable inside Docker as app:8000 But nobody outside Docker can hit it directly anymore

    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    environment: #Will use seperate redis services in production for then
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_CACHE_URL=${REDIS_CACHE_URL}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - ENV=${ENV}
      - PROD_DATABASE_URL=${PROD_DATABASE_URL}
    env_file:
      - .env
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --reload-dir /app/app

  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d # Initialize the db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d app_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  db_test:
    image: postgres:15
    container_name: postgres_db_test
    restart: always
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: password_test
      POSTGRES_DB: test_app_db
    # ports:
    #   - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d # Initialize the db

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  celery_worker:
    build: .
    depends_on:
      - redis
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_CACHE_URL=${REDIS_CACHE_URL}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    env_file:
      - .env
    command: celery -A app.tasks.celery_app.celery_app worker --loglevel=info

  migrate:
    image: postgres:15 # use this instead of build: .
    depends_on:
      postgres:
        condition: service_healthy # wait until healthcheck passes
    environment:
      - DATABASE_URL=${DATABASE_URL}
    env_file:
      - .env
    volumes:
      - ./migrations:/migrations
      - ./scripts/migrate.sh:/migrate.sh
    command: bash /migrate.sh
    restart: "no" # runs once and exits

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025" # SMTP port — your app sends emails here
      - "8025:8025" # Web UI — you view caught emails here

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090" # UI at localhost:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - app
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000" # dashboard UI at localhost:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    restart: always

  elasticsearch:
    image: elasticsearch:8.13.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    restart: always

  # (later)
  # nginx-exporter:
  #   image: nginx/nginx-prometheus-exporter:0.11.0
  #   container_name: nginx_exporter
  #   command:
  #     - -nginx.scrape-uri=http://nginx:80/nginx_status
  #   ports:
  #     - "9113:9113"
  #   depends_on:
  #     - nginx
  #   restart: always

volumes:
  postgres_data:
  postgres_test_data:
  grafana_data:
  elasticsearch_data:
